# Netlify configuration

# Build settings
[build]
  publish = "."

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/logo.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect www to non-www
[[redirects]]
  from = "https://www.letterpresslabs.com/*"
  to = "https://letterpresslabs.com/:splat"
  status = 301
  force = true

# Force HTTPS
[[redirects]]
  from = "http://letterpresslabs.com/*"
  to = "https://letterpresslabs.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.letterpresslabs.com/*"
  to = "https://letterpresslabs.com/:splat"
  status = 301
  force = true